spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    macActive: 20
    maxWait: 60000
#    schame:
#      - classpath: sql/department.sql
#      - classpath: sql/employee.sql


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
